packages:
- fedify
- amqp
- docs

catalog:
  "@logtape/logtape": ^1.0.0
  "@std/assert": "jsr:^1.0.13"
  "@std/async": "jsr:^1.0.13"
  "@std/path": "jsr:^1.0.6"
  tsdown: ^0.12.9
  typescript: ^5.8.3
