name: "Documentation Issue"
description: "Report missing, incorrect, or outdated documentation"
labels: [ "type/documentation" ]
body:
  - type: markdown
    attributes:
      value: |
        Please use this template to report issues or suggestions related to the documentation.

  - type: input
    attributes:
      label: Summary
      description: Briefly describe the documentation issue.
    validations:
      required: true

  - type: input
    attributes:
      label: Affected Docs
      description: Specify which documentation needs changes (file, section, etc.).
    validations:
      required: true

  - type: textarea
    attributes:
      label: What's Missing or Incorrect?
      description: Describe the issue with the current documentation.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested Content or Structure
      description: Suggest how the content or structure should be updated.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Related Code / Feature
      description: Reference any related code or features, if relevant.
    validations:
      required: false
