name: "Refactor or Performance or Test Issue"
description: "Suggest internal code improvements, optimizations, or test updates"
labels: [ "type/refactor", "type/performance", "type/test" ]
body:
  - type: markdown
    attributes:
      value: |
        ### Refactor
        Internal code restructuring without changing behavior.
        
        - Includes: Target area, motivation, and risk.
        - Goal: Improve maintainability or readability.
        
        ### Performance
        Optimizations aimed at improving speed or resource usage.
        
        - Includes: Before/after benchmarks, affected areas.
        - Goal: Make the system faster or more efficient.
        
        ### Test
        Improving or adding test coverage.
        
        - Includes: Scope, test strategy, and rationale.
        - Goal: Ensure stability and prevent regressions.
        
        ---
        
        Please keep only one appropriate type/* label and remove the others if present.

  - type: textarea
    attributes:
      label: Summary
      description: Briefly describe the change you're proposing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Target Area
      description: Which part of the codebase is affected?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Motivation
      description: Why does this change matter? What are you trying to improve?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Risk Assessment
      description: Is there any risk of regressions or unintended side effects?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Benefits
      description: What should be improved, simplified, or resolved as a result?
    validations:
      required: false
