$schema: ../codegen/schema.yaml
name: Application
uri: "https://www.w3.org/ns/activitystreams#Application"
extends: "https://www.w3.org/ns/activitystreams#Object"
entity: true
description: Describes a software application.
defaultContext:
- "https://www.w3.org/ns/activitystreams"
- "https://w3id.org/security/v1"
- "https://w3id.org/security/data-integrity/v1"
- "https://www.w3.org/ns/did/v1"
- "https://w3id.org/security/multikey/v1"
- manuallyApprovesFollowers: "as:manuallyApprovesFollowers"
  toot: "http://joinmastodon.org/ns#"
  featured:
    "@id": "toot:featured"
    "@type": "@id"
  discoverable: "toot:discoverable"
  suspended: "toot:suspended"
  memorial: "toot:memorial"
  indexable: "toot:indexable"
  schema: "http://schema.org#"
  PropertyValue: "schema:PropertyValue"
  value: "schema:value"

properties:
- pluralName: preferredUsernames
  singularName: preferredUsername
  singularAccessor: true
  uri: "https://www.w3.org/ns/activitystreams#preferredUsername"
  description: |
    A short username which may be used to refer to the actor,
    with no uniqueness guarantees.
  range:
  - "http://www.w3.org/2001/XMLSchema#string"
  - "http://www.w3.org/1999/02/22-rdf-syntax-ns#langString"

- pluralName: publicKeys
  singularName: publicKey
  singularAccessor: true
  uri: "https://w3id.org/security#publicKey"
  description: A public part of the key pair owned by this actor.
  untyped: true
  range:
  - "https://w3id.org/security#Key"

- pluralName: assertionMethods
  singularName: assertionMethod
  singularAccessor: true
  uri: "https://w3id.org/security#assertionMethod"
  description: |
    Represents this actor's public keys.  It serves as equivalent to
    the `publicKeys` property, but is used for [FEP-521a] compliance.

    [FEP-521a]: https://codeberg.org/fediverse/fep/src/branch/main/fep/521a/fep-521a.md
  range:
  - "https://w3id.org/security#Multikey"

- singularName: manuallyApprovesFollowers
  functional: true
  uri: "https://www.w3.org/ns/activitystreams#manuallyApprovesFollowers"
  description: |
    When `true`, conveys that for this actor, follow requests are not usually
    automatically approved, but instead are examined by a person who may accept
    or reject the request, at some time in the future.  Setting of `false`
    conveys no information and may be ignored.  This information is typically
    used to affect display of accounts, such as showing an account as private or
    locked.
  range:
  - "http://www.w3.org/2001/XMLSchema#boolean"

- singularName: inbox
  functional: true
  uri: "http://www.w3.org/ns/ldp#inbox"
  description: |
    The inbox stream contains all activities received by the actor.  The server
    SHOULD filter content according to the requester's permission.  In general,
    the owner of an inbox is likely to be able to access all of their inbox
    contents.  Depending on access control, some other content may be public,
    whereas other content may require authentication for non-owner users,
    if they can access the inbox at all.

    The server MUST perform de-duplication of activities returned by the inbox.
    Duplication can occur if an activity is addressed both to an actor's
    followers, and a specific actor who also follows the recipient actor,
    and the server has failed to de-duplicate the recipients list.
    Such deduplication MUST be performed by comparing the `id` of the activities
    and dropping any activities already seen.
  range:
  - "https://www.w3.org/ns/activitystreams#OrderedCollection"

- singularName: outbox
  functional: true
  uri: "https://www.w3.org/ns/activitystreams#outbox"
  description: |
    The outbox stream contains activities the user has published,
    subject to the ability of the requestor to retrieve the activity
    (that is, the contents of the outbox are filtered by the permissions of
    the person reading it).  If a user submits a request without
    [Authorization](https://www.w3.org/TR/activitypub/#authorization)
    the server should respond with all of the
    [Public](https://www.w3.org/TR/activitypub/#public-addressing) posts.
    This could potentially be all relevant objects published by the user,
    though the number of available items is left to the discretion of those
    implementing and deploying the server.
  range:
  - "https://www.w3.org/ns/activitystreams#OrderedCollection"

- singularName: following
  functional: true
  uri: "https://www.w3.org/ns/activitystreams#following"
  description: |
    This is a list of everybody that the actor has followed, added as a
    [side effect](https://www.w3.org/TR/activitypub/#follow-activity-outbox).
    The `following` collection MUST be either an {@link OrderedCollection}
    or a {@link Collection} and MAY be filtered on privileges of
    an authenticated user or as appropriate when no authentication is given.
  range:
  - "https://www.w3.org/ns/activitystreams#Collection"

- singularName: followers
  functional: true
  uri: "https://www.w3.org/ns/activitystreams#followers"
  description: |
    This is a list of everyone who has sent a {@link Follow} activity
    for the actor, added as a
    [side effect](https://www.w3.org/TR/activitypub/#follow-activity-outbox).
    This is where one would find a list of all the actors that are following
    the actor.  The `followers` collection MUST be either
    an {@link OrderedCollection} or a {@link Collection} and MAY be filtered on
    privileges of an authenticated user or as appropriate when no authentication
    is given.
  range:
  - "https://www.w3.org/ns/activitystreams#Collection"

- singularName: liked
  functional: true
  uri: "https://www.w3.org/ns/activitystreams#liked"
  description: |
    This is a list of every object from all of the actor's {@link Like}
    activities, added as a
    [side effect](https://www.w3.org/TR/activitypub/#like-activity-outbox).
    The `liked` collection MUST be either an {@link OrderedCollection} or
    a {@link Collection} and MAY be filtered on privileges of an authenticated
    user or as appropriate when no authentication is given.
  range:
  - "https://www.w3.org/ns/activitystreams#Collection"

- singularName: featured
  functional: true
  uri: "http://joinmastodon.org/ns#featured"
  description: |
    What is known in Mastodon as "pinned statuses", or statuses that are always
    featured at the top of people's profiles, is implemented using an extra
    property `featured` on the actor object that points to a {@link Collection}
    of objects.
  range:
  - "https://www.w3.org/ns/activitystreams#Collection"

- pluralName: streams
  singularName: stream
  singularAccessor: false
  uri: "https://www.w3.org/ns/activitystreams#streams"
  description: |
    A list of supplementary Collections which may be of interest.
  range:
  - "https://www.w3.org/ns/activitystreams#Collection"

- singularName: endpoints
  functional: true
  uri: "https://www.w3.org/ns/activitystreams#endpoints"
  description: |
    A JSON object which maps additional (typically server/domain-wide) endpoints
    which may be useful either for this actor or someone referencing this actor.
    This mapping may be nested inside the actor document as the value or may be
    a link to a JSON-LD document with these properties.
  range:
  - "https://www.w3.org/ns/activitystreams#Endpoints"

- singularName: discoverable
  functional: true
  uri: "http://joinmastodon.org/ns#discoverable"
  description: |
    Allows users to opt-in or opt-out of discoverability features like
    the profile directory.  This flag may also be used as an indicator of
    the user's preferences toward being included in external discovery services,
    such as search engines or other indexing tools.
  range:
  - "http://www.w3.org/2001/XMLSchema#boolean"

- singularName: suspended
  functional: true
  uri: "http://joinmastodon.org/ns#suspended"
  description: |
    Reports whether a user was locally suspended, for better handling of
    these accounts.
  range:
  - "http://www.w3.org/2001/XMLSchema#boolean"

- singularName: memorial
  functional: true
  uri: "http://joinmastodon.org/ns#memorial"
  description: Whether the actor is in-memorial state.
  range:
  - "http://www.w3.org/2001/XMLSchema#boolean"

- singularName: indexable
  functional: true
  uri: "http://joinmastodon.org/ns#indexable"
  description: Whether the actor allows to be indexed.
  range:
  - "http://www.w3.org/2001/XMLSchema#boolean"
